astrall_base_node:
  ros__parameters:
    sdk_ip: "10.18.0.200"
    robot_ip: "10.18.0.100"
    control_mode: "sdk"

    max_vx: 1.0
    max_vy: 0.5
    max_wz: 1.0
    cmd_vel_timeout_ms: 500

    scale_vx: 1.0
    scale_vy: 1.0
    scale_wz: 1.0
    sign_vx: 1
    sign_vy: 1
    sign_wz: 1

    publish_tf: false
    base_frame_id: "base_link"
    imu_frame_id: "imu_link"
    sdk_quaternion_order: "xyzw"

    imu_frequency_hz: 250
    sport_frequency_hz: 250
    publish_period_ms: 20
